part of 'AppPages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const OFFER = _Paths.OFFERBANNER;
  static const WELCOME = _Paths.WELCOMEBANNER;
  static const START = _Paths.GETSTART;
  static const LOGIN = _Paths.LOGIN;
  static const VERIFY = _Paths.VERIFYNUMBER;
  static const SIGNUP = _Paths.SIGNUP;
  static const RESETPASSWORDOPT = _Paths.RESETPASSWORDOPTION;
  static const RESETPHONEPASS = _Paths.RESETPHONEPASSWORD;
  static const RESETMAILPASS = _Paths.RESETMAILPASSWORD;
  static const RESETOTP = _Paths.RESETPHONEOTP;
  static const NEWPASSWORD = _Paths.NEWPASSWORDSET;
  static const TERMSPRIVACY = _Paths.TERMSSERVICE;
  static const TABBARROUTES = _Paths.TABBAR;
  static const HOMEROUTES = _Paths.HOME;
  static const SEARCHROUTES = _Paths.SEARCH;
  static const NOTIFICATIONROUTES = _Paths.NOTIFICATION;
  static const PROFILEROUTES = _Paths.PROFILE;
  static const MYPROFILEROUTES = _Paths.MYPROFILE;
  static const CONTACTUSROUTES = _Paths.CONTACTUS;
  static const PROFILESETTINGROUTES = _Paths.PROFILESETTING;
  static const PROFILEFAVORITEROUTES = _Paths.PROFILEFAVORITE;
  static const PROFILECARTROUTES = _Paths.PROFILECART;
  static const PROFILECHECKOUTROUTES = _Paths.PROFILECHECKOUT;
  static const PROFILEBUYSTATUSROUTES = _Paths.PROFILEBUYSTATUS;
  static const PROFILEBILLINGADDRESSROUTES = _Paths.PROFILEBILLINGADDRESS;
  static const PROFILENEWCREDITCARROUTES = _Paths.PROFILENEWCREDITCART;
  static const PROFILESHIPPINGADDRESSROUTES = _Paths.PROFILESHIPPINGADDRESS;
  static const PROFILEPAYMENTLISTROUTES = _Paths.PROFILEPAYMENTLIST;
  static const PROFILEMYORDERROUTES = _Paths.PROFILEMYORDERLIST;
  static const PROFILEORDERDETAILROUTES = _Paths.PROFILEORDERDETAIL;
  static const PROFILEORDERCANCELROUTES = _Paths.PROFILEORDERDCANCEL;
  static const PROFILERETURNORDERROUTES = _Paths.PROFILERETURNORDER;
  static const PROFILEREVIEWROUTES = _Paths.PROFILEREVIEW;
  static const PROFILEPRODUCTDETAILROUTES = _Paths.PROFILEPRODUCTDETAIL;
  static const PRODUCTFILTERROUTES = _Paths.PRODUCTFILTER;
  static const SEARCHRESULTROUTES = _Paths.SEARCHRESULT;
  static const MOREPRODUCTLISTROUTES = _Paths.MOREPRODUCTLIST;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const OFFERBANNER = '/OfferBanner';
  static const WELCOMEBANNER = '/WelcomeBanner';
  static const GETSTART = '/Start';
  static const LOGIN = '/login';
  static const VERIFYNUMBER = '/verify';
  static const SIGNUP = '/signup';
  static const RESETPASSWORDOPTION = '/ResetPasswordOption';
  static const RESETPHONEPASSWORD = '/ResetPhonePassword';
  static const RESETPHONEOTP = '/ResetPhoneOTP';
  static const RESETMAILPASSWORD = '/ResetMailPassword';
  static const NEWPASSWORDSET = '/NewPassword';
  static const TERMSSERVICE = '/TermsService';
  static const TABBAR = '/TabBar';
  static const HOME = '/HomeView';
  static const SEARCH = '/SearchView';
  static const NOTIFICATION = '/NotificationView';
  static const PROFILE = '/ProfileView';
  static const MYPROFILE = '/MyProfileView';
  static const CONTACTUS = '/ContactView';
  static const PROFILESETTING = '/SettingView';
  static const PROFILEFAVORITE = '/FavoriteView';
  static const PROFILECART = '/CartView';
  static const PROFILECHECKOUT = '/CheckoutView';
  static const PROFILEBUYSTATUS = '/BuyingStatusView';
  static const PROFILEBILLINGADDRESS = '/BillingAddressView';
  static const PROFILENEWCREDITCART = '/CreditCardView';
  static const PROFILESHIPPINGADDRESS = '/ShippingAddressView';
  static const PROFILEPAYMENTLIST = '/PaymentView';
  static const PROFILEMYORDERLIST = '/MyOrdersView';
  static const PROFILEORDERDETAIL = '/OrdersDetailView';
  static const PROFILEORDERDCANCEL = '/OrdersCancelView';
  static const PROFILERETURNORDER = '/ReturnOrderView';
  static const PROFILEREVIEW = '/ReviewView';
  static const PROFILEPRODUCTDETAIL = '/ProductDetailView';
  static const PRODUCTFILTER = '/FilterView';
  static const SEARCHRESULT = '/SearchResultView';
  static const MOREPRODUCTLIST = '/MoreProductView';
}
